// Copyright 2017-2021 @axia-js/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0
// Auto-generated by @axia-js/dev, do not edit
export const packageInfo = { name: '@axia-js/dev', version: '1.0.7' };
